services:
  - type: web
    name: '{{PROJECT_NAME}}'
    runtime: node
    env: node
    plan: free
    buildCommand: '{{INSTALL_COMMAND}}'
    startCommand: '{{PACKAGE_MANAGER}} start'
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: RUST_LOG
        value: info
